### ISSUE TITLE
Check withdrawing and claiming of "Pools(Closed)"

### ISSUE THREAD

**Issue by Zena-park** [Onther-Tech/tonstarter-contracts#29]
Pools(Closed) service was a service that provided TOS rewards to LPs who provided liquidity(TOS_WTON) to Uniswap V3.

It has already been terminated, but 8 accounts used the service and have not yet claimed or unstaked(withdrawn).

This service already holds the reward in the stake2VaultProxy contract assuming that liquidity was provided to the maximum.
However, suppose liquidity was not provided to the maximum, that is, if the price moved and liquidity was not provided, the reward TOS was designed to be burned instead of provided.

We have verified that the function is normal when claiming and withdrawing from accounts that have not yet withdrawn.

**Comment by Zena-park** [comment]
`npx hardhat test test/delete-tos-burnner/1.claim-from-stake-uniswap-v3-pool.test.js`
 
![스크린샷 2024-11-11 오후 5 30 07](https://github.com/user-attachments/assets/9b5e6726-50f9-45a7-b45c-ef0cdaa42e6f)

When all accounts in the above service complete withdrawal, the amount of TOS equivalent to the rewards that did not provide liquidity will be burned, so the ETH backing amount per TOS will change from 0.000073199678367128 ETH to 0.000073321163473608 ETH.

**Comment by suahnkim** [comment]
ETH backing value will be dependent on when the liquidity is burnt.
